openapi: 3.0.2
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: backlog api
security:
  -
    bearerAuth: []


paths:
  /api/v2/oauth2/token:
    post:
      summary: アクセストークンリクエスト
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/Oauth2TokenRequest"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                title: Oauth2TokenRequestResponse
                type: object
                properties:
                  access_token:
                    type: string
                    example: "YOUR_ACCESS_TOKEN"
                  token_type:
                    type: string
                    example: Bearer
                  expires_in:
                    type: number
                    example: 3600
                  refresh_token:
                    type: string
                    example: YOUR_REFRESH_TOKEN

  /api/v2/users/myself:
    get:
      summary: 認証ユーザー情報の取得
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref : '#/components/schemas/UserData'

  /api/v2/projects:
    get:
      summary: プロジェクトの一覧を取得
      parameters:
        - in: query
          name: archived
          required: false
          schema:
            type: string
            example: "true"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref : '#/components/schemas/ProjectItem'
              example:
                - archived: false
                  chartEnabled: false
                  id: 1
                  name: テストプロジェクト
                  projectKey: TEST
                  projectLeaderCanEditProjectLeader: false
                  subtaskingEnabled: false
                  textFormattingRule: markdown
                - archived: false
                  chartEnabled: false
                  id: 2
                  name: テストプロジェクト2
                  projectKey: TEST2
                  projectLeaderCanEditProjectLeader: false
                  subtaskingEnabled: false
                  textFormattingRule: markdown
components:
  schemas:
    ProjectItem:
      description: プロジェクト一覧
      example:
          archived: false
          chartEnabled: false
          id: 1
          name: テストプロジェクト
          projectKey: TEST
          projectLeaderCanEditProjectLeader: false
          subtaskingEnabled: false
          textFormattingRule: markdown
      properties:
          archived:
              default: false
              description: An explanation about the purpose of this instance.
              example:
                false
              title: The archived schema
              type: boolean
          chartEnabled:
              default: false
              description: An explanation about the purpose of this instance.
              example:
                false
              title: The chartEnabled schema
              type: boolean
          id:
              default: 0
              description: An explanation about the purpose of this instance.
              example:
                1
              title: The id schema
              type: integer
          name:
              default: ''
              description: An explanation about the purpose of this instance.
              example:
                test
              title: The name schema
              type: string
          projectKey:
              default: ''
              description: An explanation about the purpose of this instance.
              example:
                TEST
              title: The projectKey schema
              type: string
          projectLeaderCanEditProjectLeader:
              default: false
              description: An explanation about the purpose of this instance.
              example:
                false
              title: The projectLeaderCanEditProjectLeader schema
              type: boolean
          subtaskingEnabled:
              default: false
              description: An explanation about the purpose of this instance.
              example:
                false
              title: The subtaskingEnabled schema
              type: boolean
          textFormattingRule:
              default: ''
              description: An explanation about the purpose of this instance.
              example:
                markdown
              title: The textFormattingRule schema
              type: string
      required:
      - id
      - projectKey
      - name
      - chartEnabled
      - subtaskingEnabled
      - projectLeaderCanEditProjectLeader
      - textFormattingRule
      - archived
      type: object




    Oauth2TokenCodeRequest:
      type: object
      properties:
        grant_type:
          type: string
          enum:
            - authorization_code
          example: authorization_code
          description: 値は”authorization_code”で固定
        code:
          type: string
          description: 認可エンドポイントのリダイレクトから取得した認可コード 開発アプリケーション ページで設定したものと同じUri
        redirect_uri:
          type: string
          description: 認可エンドポイントで指定した場合は必須
        client_id:
          type: string
        client_secret:
          type: string
      required:
          - grant_type
          - code
          - client_id
          - client_secret

    Oauth2TokenRefleshRequest:
      type: object
      properties:
        grant_type:
          type: string
          enum:
            - refresh_token
          example: refresh_token
          description: 値は”refresh_token”で固定
        refresh_token :
          type: string
        client_id:
          type: string
        client_secret:
          type: string
      required:
          - grant_type
          - refresh_token
          - client_id
          - client_secret

    Oauth2TokenRequest:
      type: object
      properties:
        grant_type:
          type: string
          enum:
            - authorization_code
            - refresh_token
          example: authorization_code
        client_id:
          type: string
        client_secret:
          type: string
        code:
          type: string
          description: 認可エンドポイントのリダイレクトから取得した認可コード 開発アプリケーション ページで設定したものと同じUri
        redirect_uri:
          type: string
          description: 認可エンドポイントで指定した場合は必須
        refresh_token:
          type: string
      required:
          - grant_type
          - client_id
          - client_secret
    UserData:
      additionalProperties: true
      default: {}
      description: The root schema comprises the entire JSON document.
      example:
          id: 1
          lang: ja
          mailAddress: eguchi@nulab.example
          name: admin
          roleType: 1
          userId: admin
      properties:
          id:
              default: 0
              description: An explanation about the purpose of this instance.
              example: 1
              title: The id schema
              type: integer
          lang:
              default: ''
              description: An explanation about the purpose of this instance.
              example: ja
              title: The lang schema
              type: string
          mailAddress:
              default: ''
              description: An explanation about the purpose of this instance.
              example: eguchi@nulab.example
              title: The mailAddress schema
              type: string
          name:
              default: ''
              description: An explanation about the purpose of this instance.
              example: admin
              title: The name schema
              type: string
          roleType:
              default: 0
              description: An explanation about the purpose of this instance.
              example: 1
              title: The roleType schema
              type: integer
          userId:
              default: ''
              description: An explanation about the purpose of this instance.
              example: admin
              title: The userId schema
              type: string
      required:
      - id
      - name
      - roleType
      - lang
      - mailAddress
      title: The root schema
      type: object
    Status:
      description: 課題に設定できる状態
      example:
      -   color: '#ed8077'
          displayOrder: 1000
          id: 1
          name: 未対応
          projectId: 1
      properties:
          color:
              default: ''
              description: An explanation about the purpose of this instance.
              example: '#ed8077'
              title: The color schema
              type: string
          displayOrder:
              default: 0
              description: An explanation about the purpose of this instance.
              example: 1000
              title: The displayOrder schema
              type: integer
          id:
              default: 0
              description: An explanation about the purpose of this instance.
              example: 1
              title: The id schema
              type: integer
          name:
              default: ''
              description: An explanation about the purpose of this instance.
              example: 未対応
              title: The name schema
              type: string
          projectId:
              default: 0
              description: An explanation about the purpose of this instance.
              example: 1
              title: The projectId schema
              type: integer
      required:
      - id
      - projectId
      - name
      - color
      - displayOrder
      title: Status
      type: object
    Task:
      description: An explanation about the purpose of this instance.
      example:
        actualHours: null
        assignee:
            id: 2
            lang: null
            mailAddress: eguchi@nulab.example
            name: eguchi
            roleType: 2
        attachments:
        -   id: 1
            name: IMGP0088.JPG
            size: 85079
        category: []
        created: '2012-07-23T06:10:15Z'
        createdUser:
            id: 1
            lang: ja
            mailAddress: eguchi@nulab.example
            name: admin
            roleType: 1
            userId: admin
        customFields: []
        description: ''
        dueDate: null
        estimatedHours: null
        id: 1
        issueKey: BLG-1
        issueType:
            color: '#7ea800'
            displayOrder: 0
            id: 2
            name: タスク
            projectId: 1
        keyId: 1
        milestone:
        -   archived: false
            description: ''
            displayOrder: 0
            id: 30
            name: wait for release
            projectId: 1
            releaseDueDate: null
            startDate: null
        parentIssueId: null
        priority:
            id: 3
            name: 中
        projectId: 1
        resolutions: null
        sharedFiles:
        -   created: '2009-02-27T03:26:15Z'
            createdUser:
                id: 5686
                lang: ja
                mailAddress: takada@nulab.example
                name: takada
                roleType: 2
                userId: takada
            dir: /ユーザアイコン/
            id: 454403
            name: 01_サラリーマン.png
            size: 2735
            type: file
            updated: '2009-03-03T16:57:47Z'
            updatedUser:
                id: 5686
                lang: ja
                mailAddress: takada@nulab.example
                name: takada
                roleType: 2
                userId: takada
        stars:
        -   comment: null
            created: '2013-07-08T10:24:28Z'
            id: 10
            presenter:
                id: 2
                lang: ja
                mailAddress: eguchi@nulab.example
                name: eguchi
                roleType: 2
                userId: eguchi
            title: '[BLG-1] first issue | 課題の表示 - Backlog'
            url: https://xx.backlog.jp/view/BLG-1
        startDate: null
        status:
            color: '#ed8077'
            displayOrder: 1000
            id: 1
            name: 未対応
            projectId: 1
        summary: first issue
        updated: '2013-02-07T08:09:49Z'
        updatedUser:
            id: 1
            lang: ja
            mailAddress: eguchi@nulab.example
            name: admin
            roleType: 1
            userId: admin
        versions: []
      properties:
          actualHours:
              description: An explanation about the purpose of this instance.
              example: null
              title: The actualHours schema
              nullable: true
              type: string
          assignee:
              $ref : '#/components/schemas/UserData'
          attachments:
              default: []
              description: An explanation about the purpose of this instance.
              example:
                  -   id: 1
                      name: IMGP0088.JPG
                      size: 85079
              items:
                  $ref : '#/components/schemas/Attachment'
              type: array
          category:
              default: []
              description: An explanation about the purpose of this instance.
              example: []
              title: The category schema
              items:
                type: string
              type: array
          created:
              description: An explanation about the purpose of this instance.
              example:
                '2012-07-23T06:10:15Z'
              title: The created schema
              type: string
              format: date-time
          createdUser:
              $ref : '#/components/schemas/UserData'
          customFields:
              default: []
              description: An explanation about the purpose of this instance.
              example:
                []
              title: The customFields schema
              items:
                type: string
              type: array
          description:
              default: ''
              description: An explanation about the purpose of this instance.
              example:
                ''
              title: The description schema
              type: string
          dueDate:
              description: An explanation about the purpose of this instance.
              example:
                null
              title: The dueDate schema
              type: string
              format: date-time
              nullable: true
          estimatedHours:
              description: An explanation about the purpose of this instance.
              example:
                null
              title: The estimatedHours schema
              type: number
              nullable: true
          id:
              default: 0
              description: An explanation about the purpose of this instance.
              example:
                1
              title: The id schema
              type: integer
          issueKey:
              default: ''
              description: An explanation about the purpose of this instance.
              example:
                BLG-1
              title: The issueKey schema
              type: string
          issueType:
              $ref : '#/components/schemas/IssueType'
          keyId:
              default: 0
              description: An explanation about the purpose of this instance.
              example:
                1
              title: The keyId schema
              type: integer
          milestone:
              default: []
              description: An explanation about the purpose of this instance.
              example:
                  -   archived: false
                      description: ''
                      displayOrder: 0
                      id: 30
                      name: wait for release
                      projectId: 1
                      releaseDueDate: null
                      startDate: null
              items:
                $ref : '#/components/schemas/Milestone'
              title: The milestone schema
              type: array
          parentIssueId:
              description: An explanation about the purpose of this instance.
              example:
                null
              title: The parentIssueId schema
              nullable: true
              type: string
          priority:
            $ref : '#/components/schemas/Priority'
          projectId:
              default: 0
              description: An explanation about the purpose of this instance.
              example:
                1
              title: The projectId schema
              type: integer
          resolutions:
              description: An explanation about the purpose of this instance.
              example:
                null
              title: The resolutions schema
              nullable: true
              type: string
          sharedFiles:
              default: []
              description: An explanation about the purpose of this instance.
              example:
                  -   created: '2009-02-27T03:26:15Z'
                      createdUser:
                          id: 5686
                          lang: ja
                          mailAddress: takada@nulab.example
                          name: takada
                          roleType: 2
                          userId: takada
                      dir: /ユーザアイコン/
                      id: 454403
                      name: 01_サラリーマン.png
                      size: 2735
                      type: file
                      updated: '2009-03-03T16:57:47Z'
                      updatedUser:
                          id: 5686
                          lang: ja
                          mailAddress: takada@nulab.example
                          name: takada
                          roleType: 2
                          userId: takada
              items:
                  $ref : '#/components/schemas/SharedFile'
              type: array
          stars:
              default: []
              description: An explanation about the purpose of this instance.
              example:
                  -   comment: null
                      created: '2013-07-08T10:24:28Z'
                      id: 10
                      presenter:
                          id: 2
                          lang: ja
                          mailAddress: eguchi@nulab.example
                          name: eguchi
                          roleType: 2
                          userId: eguchi
                      title: '[BLG-1] first issue | 課題の表示 - Backlog'
                      url: https://xx.backlog.jp/view/BLG-1
              items:
                  $ref : '#/components/schemas/Star'

              title: The stars schema
              type: array
          startDate:
              description: An explanation about the purpose of this instance.
              example:
                null
              title: The startDate schema
              type: string
              format: date-time
              nullable: true
          status:
            $ref : '#/components/schemas/Status'

          summary:
              default: ''
              description: An explanation about the purpose of this instance.
              example:
                first issue
              title: The summary schema
              type: string
          updated:
              description: An explanation about the purpose of this instance.
              example:
                '2013-02-07T08:09:49Z'
              title: The updated schema
              type: string
              format: date-time
          updatedUser:
              $ref : '#/components/schemas/UserData'
          versions:
              default: []
              description: An explanation about the purpose of this instance.
              example:
                []
              items:
                  type: string
              title: The versions schema
              type: array
      required:
      - id
      - projectId
      - issueKey
      - keyId
      - issueType
      - summary
      - description
      - resolutions
      - priority
      - status
      - assignee
      - category
      - versions
      - milestone
      - startDate
      - dueDate
      - estimatedHours
      - actualHours
      - parentIssueId
      - createdUser
      - created
      - updatedUser
      - updated
      - customFields
      - attachments
      - sharedFiles
      - stars
      type: object

    Attachment:
      additionalProperties: true
      default: {}
      description: An explanation about the purpose of this instance.
      example:
          id: 1
          name: IMGP0088.JPG
          size: 85079
      properties:
          id:
              default: 0
              description: An explanation about the purpose of this
                  instance.
              example:
                1
              title: The id schema
              type: integer
          name:
              default: ''
              description: An explanation about the purpose of this
                  instance.
              example:
                IMGP0088.JPG
              title: The name schema
              type: string
          size:
              default: 0
              description: An explanation about the purpose of this
                  instance.
              example:
                85079
              title: The size schema
              type: integer
      required:
      - id
      - name
      - size
      title: The first anyOf schema
      type: object
    IssueType:
      additionalProperties: true
      default: {}
      description: An explanation about the purpose of this instance.
      example:
          color: '#7ea800'
          displayOrder: 0
          id: 2
          name: タスク
          projectId: 1
      properties:
          color:
              default: ''
              description: An explanation about the purpose of this instance.
              example:
              - '#7ea800'
              title: The color schema
              type: string
          displayOrder:
              default: 0
              description: An explanation about the purpose of this instance.
              example:
              - 0
              title: The displayOrder schema
              type: integer
          id:
              default: 0
              description: An explanation about the purpose of this instance.
              example:
              - 2
              title: The id schema
              type: integer
          name:
              default: ''
              description: An explanation about the purpose of this instance.
              example:
              - タスク
              title: The name schema
              type: string
          projectId:
              default: 0
              description: An explanation about the purpose of this instance.
              example:
              - 1
              title: The projectId schema
              type: integer
      required:
      - id
      - projectId
      - name
      - color
      - displayOrder
      type: object

    Milestone:
      default: {}
      description: An explanation about the purpose of this instance.
      example:
          archived: false
          description: ''
          displayOrder: 0
          id: 30
          name: wait for release
          projectId: 1
          releaseDueDate: null
          startDate: null
      properties:
          archived:
              default: false
              description: An explanation about the purpose of this
                  instance.
              example:
              - false
              title: The archived schema
              type: boolean
          description:
              default: ''
              description: An explanation about the purpose of this
                  instance.
              example:
              - ''
              title: The description schema
              type: string
          displayOrder:
              default: 0
              description: An explanation about the purpose of this
                  instance.
              example:
              - 0
              title: The displayOrder schema
              type: integer
          id:
              default: 0
              description: An explanation about the purpose of this
                  instance.
              example:
              - 30
              title: The id schema
              type: integer
          name:
              default: ''
              description: An explanation about the purpose of this
                  instance.
              example:
              - wait for release
              title: The name schema
              type: string
          projectId:
              default: 0
              description: An explanation about the purpose of this
                  instance.
              example:
              - 1
              title: The projectId schema
              type: integer
          releaseDueDate:
              description: An explanation about the purpose of this
                  instance.
              example:
              - null
              title: The releaseDueDate schema
              nullable: true
              type: string
              format: date-time
          startDate:
              description: An explanation about the purpose of this
                  instance.
              example:
              - null
              title: The startDate schema
              nullable: true
              type: string
              format: date-time
      required:
      - id
      - projectId
      - name
      - description
      - startDate
      - releaseDueDate
      - archived
      - displayOrder
      title: The first anyOf schema
      type: object

    Priority:
      additionalProperties: true
      default: {}
      description: An explanation about the purpose of this instance.
      example:
          id: 3
          name: 中
      properties:
          id:
              default: 0
              description: An explanation about the purpose of this instance.
              example:
              - 3
              title: The id schema
              type: integer
          name:
              default: ''
              description: An explanation about the purpose of this instance.
              example:
              - 中
              title: The name schema
              type: string
      required:
      - id
      - name
      title: The priority schema
      type: object
    SharedFile:
      additionalProperties: true
      default: {}
      description: An explanation about the purpose of this instance.
      example:
        created: '2009-02-27T03:26:15Z'
        createdUser:
            id: 5686
            lang: ja
            mailAddress: takada@nulab.example
            name: takada
            roleType: 2
            userId: takada
        dir: /ユーザアイコン/
        id: 454403
        name: 01_サラリーマン.png
        size: 2735
        type: file
        updated: '2009-03-03T16:57:47Z'
        updatedUser:
            id: 5686
            lang: ja
            mailAddress: takada@nulab.example
            name: takada
            roleType: 2
            userId: takada
      properties:
          created:
              default: ''
              description: An explanation about the purpose of this
                  instance.
              example:
              - '2009-02-27T03:26:15Z'
              title: The created schema
              type: string
          createdUser:
            $ref : '#/components/schemas/UserData'
          dir:
              default: ''
              description: An explanation about the purpose of this
                  instance.
              example:
              - /ユーザアイコン/
              title: The dir schema
              type: string
          id:
              default: 0
              description: An explanation about the purpose of this
                  instance.
              example:
              - 454403
              title: The id schema
              type: integer
          name:
              default: ''
              description: An explanation about the purpose of this
                  instance.
              example:
              - 01_サラリーマン.png
              title: The name schema
              type: string
          size:
              default: 0
              description: An explanation about the purpose of this
                  instance.
              example:
              - 2735
              title: The size schema
              type: integer
          type:
              default: ''
              description: An explanation about the purpose of this
                  instance.
              example:
              - file
              title: The type schema
              type: string
          updated:
              default: ''
              description: An explanation about the purpose of this
                  instance.
              example:
              - '2009-03-03T16:57:47Z'
              title: The updated schema
              type: string
          updatedUser:
            $ref : '#/components/schemas/UserData'
      required:
      - id
      - type
      - dir
      - name
      - size
      - createdUser
      - created
      - updatedUser
      - updated
      title: The first anyOf schema
      type: object

    Star:
      additionalProperties: true
      description: An explanation about the purpose of this instance.
      example:
          comment: null
          created: '2013-07-08T10:24:28Z'
          id: 10
          presenter:
              id: 2
              lang: ja
              mailAddress: eguchi@nulab.example
              name: eguchi
              roleType: 2
              userId: eguchi
          title: '[BLG-1] first issue | 課題の表示 - Backlog'
          url: https://xx.backlog.jp/view/BLG-1
      properties:
          comment:
              description: An explanation about the purpose of this
                  instance.
              example:
              - null
              title: The comment schema
              nullable: true
              type: string
          created:
              default: ''
              description: An explanation about the purpose of this
                  instance.
              example:
              - '2013-07-08T10:24:28Z'
              title: The created schema
              type: string
          id:
              default: 0
              description: An explanation about the purpose of this
                  instance.
              example:
              - 10
              title: The id schema
              type: integer
          presenter:
            $ref : '#/components/schemas/UserData'
          title:
              default: ''
              description: An explanation about the purpose of this
                  instance.
              example:
              - '[BLG-1] first issue | 課題の表示 - Backlog'
              title: The title schema
              type: string
          url:
              default: ''
              description: An explanation about the purpose of this
                  instance.
              example:
              - https://xx.backlog.jp/view/BLG-1
              title: The url schema
              type: string
      required:
      - id
      - comment
      - url
      - title
      - presenter
      - created
      title: The first anyOf schema
      type: object

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
